server:
  port: 8002
spring:
  application:
    name: cloud-payment-service #服务模块名
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #nacos管理地址
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2024?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: yuhu

#management:
#  endpoints:
#    web:
#      exposure:
#        include: *

# ========================mybatis===================
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.cloud.entities
  configuration:
    map-underscore-to-camel-case: true